// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd2wZx-3eekCnTYmkFkUAjLL5zplXUCrI',
    appId: '1:699763310876:web:fe92c8085ddd502e8cfad9',
    messagingSenderId: '699763310876',
    projectId: 'mobile-9e2a1',
    authDomain: 'mobile-9e2a1.firebaseapp.com',
    databaseURL: 'https://mobile-9e2a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-9e2a1.firebasestorage.app',
    measurementId: 'G-YYRPJM0XYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTzDLGIwey8wGJrTYrHARg0IA8erKDHgw',
    appId: '1:699763310876:android:1cd53e3c02780d698cfad9',
    messagingSenderId: '699763310876',
    projectId: 'mobile-9e2a1',
    databaseURL: 'https://mobile-9e2a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-9e2a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-e6P72HcZrov4DjvBy_lSXZI4vTLgk6c',
    appId: '1:699763310876:ios:dc5e0f42ab39ef668cfad9',
    messagingSenderId: '699763310876',
    projectId: 'mobile-9e2a1',
    databaseURL: 'https://mobile-9e2a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-9e2a1.firebasestorage.app',
    iosClientId: '699763310876-lmbqhg1o7lj3jrua0osht08tntuelnin.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-e6P72HcZrov4DjvBy_lSXZI4vTLgk6c',
    appId: '1:699763310876:ios:dc5e0f42ab39ef668cfad9',
    messagingSenderId: '699763310876',
    projectId: 'mobile-9e2a1',
    databaseURL: 'https://mobile-9e2a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-9e2a1.firebasestorage.app',
    iosClientId: '699763310876-lmbqhg1o7lj3jrua0osht08tntuelnin.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd2wZx-3eekCnTYmkFkUAjLL5zplXUCrI',
    appId: '1:699763310876:web:95b90719474f419c8cfad9',
    messagingSenderId: '699763310876',
    projectId: 'mobile-9e2a1',
    authDomain: 'mobile-9e2a1.firebaseapp.com',
    databaseURL: 'https://mobile-9e2a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mobile-9e2a1.firebasestorage.app',
    measurementId: 'G-N8FQP114ZW',
  );

}